(use spork/test)
(import /notes)

(start-suite :docs)
(assert-docs "/notes")
(end-suite)

(defn s [title & body] [:section [:h2 title] ;body])
(def a (s "A"))
(def b (s "B"))
(def c (s "C"))
(def d (s "D"))
(def x (s "X"))

(start-suite :heading)
(assert (= "Tools" (notes/slide/heading [:section [:p "intro"] [:h2 "Tools"]]))
        "A slide is known by its first heading")
(assert (= "Hello world" (notes/slide/heading [:section [:h1 "Hello " [:code "world"]]]))
        "all of its text")
(assert (nil? (notes/slide/heading [:section [:p "no heading"]])) "or by none")
(end-suite)

(start-suite :matched)
(defn matched [old new] (notes/slides/matched old new))
(assert (deep= @{0 0 1 1 2 2} (matched [a b c] [a b c])) "Nothing changed, nothing moved")
(assert (deep= @{0 0 1 2 2 3} (matched [a b c] [a x b c])) "A slide put in moves those after it")
(assert (deep= @{0 0 2 1} (matched [a b c] [a c])) "A slide taken out goes nowhere")
(assert (deep= @{0 0 1 1 2 2} (matched [a b c] [a (s "B" [:p "more"]) c]))
        "A slide edited in place stays")
(assert (deep= @{0 0 1 2 2 3}
               (matched [a b c] [a x (s "B" [:p "more"]) c]))
        "and keeps its heading when a slide is put in beside it")
(assert (deep= @{0 0 2 3} (matched [a b c] [a x (s "Y") c]))
        "A slide replaced by two others is neither of them")
(assert (deep= @{0 1 1 2} (matched [a b c] [c a b]))
        "Slides moved about keep the order they can")
(assert (deep= @{} (matched [a b] [])) "An emptied deck keeps nothing")
(end-suite)

(start-suite :reanchored)
(defn note [text slide] @{:text text :anchor slide})
(let [[placed orphans] (notes/reanchored @{1 (note "about B" b) 2 (note "about C" c)}
                                         [a b c] [a x b c])]
  (assert (deep= "about B" (get-in placed [2 :text])) "A note follows its slide")
  (assert (deep= "about C" (get-in placed [3 :text])) "every one of them")
  (assert (empty? orphans) "and none is lost"))
(let [edited (s "B" [:p "more"])
      [placed _] (notes/reanchored @{1 (note "about B" b)} [a b c] [a edited c])]
  (assert (deep= edited (get-in placed [1 :anchor]))
          "A note on a slide edited in place is anchored to it as it is now"))
(let [[placed orphans] (notes/reanchored @{2 (note "about C" c)} [a b c] [c a b])]
  (assert (= "about C" (get-in placed [0 :text]))
          "A slide moved out of order is found by what it is")
  (assert (empty? orphans) "and its note with it"))
(let [[placed orphans] (notes/reanchored @{1 (note "about B" b)} [a b c] [a c])]
  (assert (empty? placed) "A note whose slide is gone is on no slide")
  (assert (deep= @[@{:text "about B" :anchor b :was 1}] orphans)
          "but kept, with the slide it was written on"))
(let [[placed orphans] (notes/reanchored @{0 (note "about C" c)} nil [a b c d c])]
  (assert (= "about C" (get-in placed [2 :text]))
          "A deck come back finds a note's slide by what it is, the nearest one")
  (assert (empty? orphans) "and loses nothing it can find"))
(let [[_ orphans] (notes/reanchored @{0 (note "about X" x)} nil [a b])]
  (assert (= 1 (length orphans)) "and keeps what it cannot"))
(end-suite)

(start-suite :changed)
(def deck {:title "T" :slides [a b c]})
(def held @{:slides @{} :orphans @[@{:id "o1" :text "lost" :anchor x :was 4}]})
(assert (nil? (notes/changed held deck [:write "t" 1 "say hi"])) "A note is written")
(assert (deep= @{:text "say hi" :anchor b} (get-in held [:slides 1])) "on its slide")
(assert (= "There is no such slide." (notes/changed held deck [:write "t" 9 "x"]))
        "but not past the last slide")
(assert (nil? (notes/changed held deck [:attach "t" "o1" 1])) "An orphan is attached")
(assert (= "say hi\n\nlost" (get-in held [:slides 1 :text]))
        "after what the slide's note said")
(assert (empty? (held :orphans)) "and is an orphan no more")
(assert (= "There is no such note." (notes/changed held deck [:drop "t" "o1"]))
        "An orphan is attached once")
(notes/changed held deck [:write "t" 1 "  \n"])
(assert (nil? (get-in held [:slides 1])) "A blank note is no note")
(let [projected (notes/projected @{"t" held})]
  (assert (deep= @{} (get-in projected ["t" :slides])) "The presenter is given the texts"))
(notes/changed held deck [:write "t" 0 "first"])
(assert (deep= @{0 "first"} (get-in (notes/projected @{"t" held}) ["t" :slides]))
        "and nothing of the anchors")
(end-suite)
