(def conf-file "test/conf.tree.test.jdn")
(os/setenv "CONF" conf-file)
(use spork/test /environment /schema gp/net/rpc)
(def conf (parse (slurp conf-file)))
(def {:rpc rpc-url :psk psk} conf)

(import /tree)

(start-suite :docs)
(assert-docs "/tree")
(end-suite)

(def three @{:title "Three" :slides @[[:section [:h1 "One"]]
                                      [:section [:h1 "Two"]]
                                      [:section [:h1 "Three"]]]})
(def one @{:title "One" :slides @[[:section [:h1 "Only"]]]})

(start-suite :stage)
(def decks {"three" three "one" one})
(defn moved [stage & move] (tree/stage/moved decks stage move))
(defn on [n shown] {:presentation "three" :slide n :presenting shown})
(assert (deep= [:ok (on 0 false)] (moved nil :stage "three"))
        "A deck is staged on its first slide, unseen")
(assert (deep= [:ok (on 1 false)] (moved (on 0 false) :next))
        "Next moves one on, and shows the students nothing")
(assert (deep= [:ok (on 1 true)] (moved (on 1 false) :present))
        "Presenting shows the slide the lecturer is on")
(assert (deep= [:ok (on 2 true)] (moved (on 1 true) :next)) "and every one after it")
(assert (deep= [:ok (on 2 true)] (moved (on 2 true) :next))
        "Next on the last slide stays there")
(assert (deep= [:ok (on 0 false)] (moved (on 0 false) :previous))
        "Previous on the first slide stays there")
(assert (deep= [:ok (on 2 false)] (moved nil :goto "three" 9)) "Going too far lands on the last")
(assert (deep= [:ok (on 0 true)] (moved (on 2 true) :goto "three" 0))
        "Going about the deck presented goes on presenting")
(assert (deep= [:ok {:presentation "one" :slide 0 :presenting false}]
               (moved (on 2 true) :goto "one" 0))
        "and going to another deck stages it, unseen")
(assert (deep= [:ok (on 2 false)] (moved (on 2 true) :stop))
        "Stopping hides the slides, and the deck stays")
(assert (deep= [:ok nil] (moved (on 2 false) :close)) "Closing clears the stage")
(assert (= :refused (first (moved nil :next))) "Nothing to move when nothing is staged")
(assert (= :refused (first (moved nil :present))) "nor to present")
(assert (= :refused (first (moved nil :stage "four"))) "An unknown deck cannot be staged")
(end-suite)

(start-suite :live)
(let [live (tree/live/of {"three" three} (on 1 true))]
  (assert (deep= [:section [:h1 "Two"]] (live :content)) "The live slide is the staged one")
  (assert (= 3 (live :count)) "and says how many there are")
  (assert (= "Three" (live :title)) "and whose they are")
  (assert (nil? (live :slides)) "A watcher is never given the rest of the deck"))
(assert (deep= {:presentation "three" :title "Three"} (tree/live/of {"three" three} (on 1 false)))
        "Of a deck staged but not presented, a watcher is given the title alone")
(let [parted @{:title "Course"
               :sections @[@{:title "Intro" :date "2024-02-26" :first 0 :count 2}
                           @{:title "Tools" :date "2024-02-27" :first 2 :count 1}]
               :slides (three :slides)}
      live (tree/live/of {"course" parted} {:presentation "course" :slide 2 :presenting true})]
  (assert (= ["Course" "Tools" "2024-02-27"] [(live :title) (live :section) (live :date)])
          "The live slide says which section it is in, and when that was"))
(assert (nil? (tree/live/of {"three" three} nil)) "Nothing is live on an empty stage")
(assert (nil? (tree/live/of {} {:presentation "gone" :slide 0}))
        "Nor on a stage whose deck is gone")
(end-suite)

(ev/sleep 0.01) # Settle the server
(setdyn :ctx ctx)

(start-suite :rpc)
(let [t (client ;(server/host-port rpc-url) "test" psk)]
  (defn move [& m] (:stage/move t ;m))
  (assert (= :ok (:save-presentation t "three" three)) "A deck is kept")
  (assert (= "Three" (get-in (:presentations t) ["three" :title])) "and can be read back")
  (assert-not (first (protect (:save-presentation t "bad" @{:title "No slides"})))
              "A deck without slides is refused")
  (assert-not (first (protect (:save-presentation t "../etc" one)))
              "An id naming another place is refused")
  (def first-revision ((:snapshot t [:stage]) :revision))

  (assert (= :ok (:build-failed t "three" {:file "three.md" :line 4 :message "Oops"}))
          "A failed build is recorded")
  (assert (= 4 (get-in (:errors t) ["three" :line])) "with its line")
  (assert (:presentations t) "The deck built before stays")
  (:save-presentation t "three" three)
  (assert (nil? (get (:errors t) "three")) "A good build forgets the error")

  (let [{:status status :stage stage} (move :stage "three")]
    (assert (= :ok status) "A deck is staged")
    (assert (deep= {:presentation "three" :slide 0 :presenting false} stage)
            "on the first slide"))
  (assert (deep= {:presentation "three" :title "Three"} (:live t))
          "and the watchers are given its title alone")
  (move :next)
  (assert (deep= {:presentation "three" :title "Three"} (:live t))
          "Paging through a staged deck shows them nothing more")
  (move :previous)
  (move :present)
  (assert (deep= [:section [:h1 "One"]] ((:live t) :content))
          "Presenting it, the watcher's shadow follows")
  (move :next) (move :next) (move :next)
  (assert (= 2 ((:stage t) :slide)) "A clicker pressed too often stays on the last slide")
  (assert (= :refused ((move :stage "nope") :status)) "An unknown deck is refused")
  (assert (= :refused ((move :jump) :status)) "So is an unknown move")

  (:save-presentation t "three" one)
  (assert (= 0 ((:stage t) :slide))
          "A deck rebuilt shorter under the stage keeps it on a slide that exists")
  (assert (deep= [:section [:h1 "Only"]] ((:live t) :content)) "and shows the new slide")
  (assert ((:stage t) :presenting) "still presented")

  (let [snap (:snapshot t [:stage :live])]
    (assert (string? (snap :epoch)) "A snapshot names the tree it saw")
    (assert (> (snap :revision) first-revision) "and moves on with every change")
    (assert (= "three" (get-in snap [:values :stage :presentation]))
            "and carries what was asked"))
  (assert-not (first (protect (:snapshot t [:sessions]))) "Sessions are not projected")

  (:remove-presentation t "three")
  (assert (false? (:stage t)) "Removing the staged deck clears the stage")
  (assert (false? (:live t)) "and the watchers see nothing, said as false")

  (def a [:section [:h2 "A"]])
  (def b [:section [:h2 "B"]])
  (def c [:section [:h2 "C"]])
  (defn note [& change] (:notes/change t ;change))
  (defn held [] (get (:notes t) "abc"))
  (:save-presentation t "abc" @{:title "ABC" :slides @[a b c]})
  (assert (= :ok ((note :write "abc" 1 "about B") :status)) "A note is written")
  (assert (deep= @{1 "about B"} ((held) :slides)) "on its slide")
  (assert (= "about B" (get-in (:snapshot t [:notes]) [:values :notes "abc" :slides 1]))
          "and projected to whoever asks for the notes")
  (assert (= :refused ((note :write "abc" 3 "past") :status)) "Past the last slide it is refused")
  (assert (= :refused ((note :write "nope" 0 "x") :status)) "and so it is on no deck")
  (assert (= :refused ((note :write "abc" 0 42) :status)) "A note is text")
  (note :write "abc" 2 "about C")
  (:save-presentation t "abc" @{:title "ABC" :slides @[a [:section [:h2 "X"]] b c]})
  (assert (deep= @{2 "about B" 3 "about C"} ((held) :slides))
          "A slide put in before them moves the notes with their slides")
  (:save-presentation t "abc" @{:title "ABC" :slides @[a b]})
  (assert (deep= @{1 "about B"} ((held) :slides)) "A slide taken out takes its note off")
  (def [orphan] ((held) :orphans))
  (assert (= "about C" (orphan :text)) "and keeps it aside")
  (assert (deep= c (orphan :anchor)) "with the slide it was written on")
  (assert (= :ok ((note :attach "abc" (orphan :id) 0) :status)) "An orphan is put on a slide")
  (assert (deep= @{0 "about C" 1 "about B"} ((held) :slides)) "the one asked for")
  (assert (empty? ((held) :orphans)) "and is an orphan no more")
  (:remove-presentation t "abc")
  (:save-presentation t "abc" @{:title "ABC" :slides @[a b]})
  (assert (deep= @{0 "about C" 1 "about B"} ((held) :slides))
          "A deck whose file was gone for a while comes back to its notes")

  (defn cookie [session] @{:headers @{"Cookie" @{"session" session}}})
  (assert (= :applied (get (:session/new t "abcd" :presenter/sentry) :status))
          "A session is applied before it is acknowledged")
  (assert ((:cap/session t :presenter/sentry) (cookie "abcd"))
          "The presenter's door opens to it")
  (assert-not ((:cap/session t :presenter/sentry) (cookie "wxyz"))
              "and to no other")
  (assert-not ((:cap/session t :watcher) (cookie "abcd"))
              "Nobody granted the watcher a session")
  (let [cap (:register t :presenter :presenter/sentry)]
    (assert (cap (cookie "abcd"))
            "Registering answers with the session of the peer's door"))
  # The goodbye every departing peer says. Without it the tree goes on
  # dialling an address nobody answers, and on Windows a refused connect
  # holds the whole event loop for two seconds each time.
  (assert (= :ok (:deregister t :presenter)) "A peer says goodbye")
  (let [s (os/clock)]
    (:stage t)
    (assert (< (- (os/clock) s) 0.5) "and the tree stops dialling it"))
  (:session/new t "" :presenter/sentry)
  (assert-not ((:cap/session t :presenter/sentry) (cookie ""))
              "An ended session opens nothing"))
(end-suite)
